// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFhxcCBepgcH_YgpiMMu3Voijm_j7Iw9A',
    appId: '1:864017662235:web:2057ee07af1be0da63d3be',
    messagingSenderId: '864017662235',
    projectId: 'notifanalytics',
    authDomain: 'notifanalytics.firebaseapp.com',
    storageBucket: 'notifanalytics.firebasestorage.app',
    databaseURL: 'https://notifanalytics-default-rtdb.firebaseio.com',
    measurementId: 'G-53RR71VYL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi1c6ZOKnjfe6LnNHRA3MBPk2tQ_7fun8',
    appId: '1:864017662235:android:2c606c778c36b74563d3be',
    messagingSenderId: '864017662235',
    projectId: 'notifanalytics',
    storageBucket: 'notifanalytics.firebasestorage.app',
    databaseURL: 'https://notifanalytics-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADnArFCi__m5NHF_L7OBpCmFCNHTPZYng',
    appId: '1:864017662235:ios:3bbb73e8a2c6d3a063d3be',
    messagingSenderId: '864017662235',
    projectId: 'notifanalytics',
    storageBucket: 'notifanalytics.firebasestorage.app',
    databaseURL: 'https://notifanalytics-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.notifAnalytics',
  );
}
